use_frameworks!

platform :ios, '8.0'

target 'TuWaterWave_Example' do
  pod 'TuWaterWave', :path => '../'

  target 'TuWaterWave_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
